# Generated by Django 3.2.5 on 2021-08-04 05:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('cover', models.ImageField(upload_to='imcovers/')),
                ('distro', models.CharField(max_length=255)),
                ('interface', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
